#-------------------------------------------------------------------------------------------------
# Description : AWS Codebuild-build spec file
# Author      : Sergey Sakhno
#-------------------------------------------------------------------------------------------------

version: 0.2
env:
  variables:
    PGTEST_DBURL: jdbc:postgresql://localhost:5432/devopstasks
    PGTEST_DBUSER: devopstasks
    PGTEST_DBPASSWORD: pass

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build: # Check availability of Maven and it's version
    commands:
      - "echo -e '\nMaven version: '"
      - "mvn --version"
  build: # Build Docker image and tag it with the commit sha and latest
    commands:
      - echo Starting postgres
      - docker run -e POSTGRES_USER=$PGTEST_DBUSER -e POSTGRES_PASSWORD=$PGTEST_DBPASSWORD -d -p 5432:5432 public.ecr.aws/docker/library/postgres:latest
      - echo Starting build and test
      - mvn clean package -Dspring.profiles.active=prodtest
      - echo 'Target folder files:'
      - ls target -l -r
      - docker build . -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION -f ./DevOps/AWS/EKS/Dockerfile
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest