plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1

include_filters:
  - tag:Application:
      - 'DevOpsTasks'
    tag:Service:
      - 'WebServer'

hostnames:
  - private-ip-address

keyed_groups:
  - key: tags['Environment']
    prefix: Environment

compose:
  ansible_host: private_ip_address

